version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=spiritus-lectoris
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data